Connected to Python 3.14.3

In [ ]:
import numpy as np

In [ ]:
time_series = np.cos(np.linspace(0, 2*np.pi, 4, endpoint=False))

In [ ]:
np.linspace(0, 2*np.pi, 4, endpoint=False)

array([0.        , 1.57079633, 3.14159265, 4.71238898])

In [ ]:
time_series

array([ 1.0000000e+00,  6.1232340e-17, -1.0000000e+00, -1.8369702e-16])

In [ ]:
time_series = np.cos(np.linspace(0, 2*np.pi, 5, endpoint=False))

In [ ]:
np.round(np.fft.fft(time_series), 5)

array([-0. +0.j,  2.5-0.j,  0. -0.j,  0. +0.j,  2.5+0.j])

In [ ]:
np.round(np.fft.fft(time_series), 5)/len(np.linspace(0, 2*np.pi, 5, endpoint=False))

array([0. +0.j, 0.5-0.j, 0. -0.j, 0. +0.j, 0.5+0.j])

In [ ]:
N = 10
time_series = np.cos(np.linspace(0, 2*np.pi, N, endpoint=False))
np.round(np.fft.fft(time_series), 5)

array([-0.+0.j,  5.-0.j,  0.+0.j,  0.+0.j, -0.+0.j, -0.-0.j, -0.+0.j,
        0.-0.j,  0.+0.j,  5.+0.j])

In [ ]:
N = 100
time_series = np.cos(np.linspace(0, 2*np.pi, N, endpoint=False))
np.round(np.fft.fft(time_series), 5)

array([ 0.+0.j, 50.+0.j, -0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j, -0.-0.j,
        0.-0.j, -0.+0.j, -0.-0.j,  0.+0.j, -0.+0.j,  0.-0.j,  0.-0.j,
       -0.+0.j, -0.+0.j, -0.+0.j, -0.-0.j,  0.-0.j,  0.+0.j, -0.+0.j,
       -0.-0.j,  0.+0.j, -0.+0.j, -0.+0.j, -0.-0.j,  0.-0.j,  0.+0.j,
        0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j,  0.-0.j,  0.+0.j,  0.+0.j,
        0.-0.j, -0.-0.j, -0.+0.j,  0.+0.j, -0.-0.j, -0.-0.j,  0.-0.j,
        0.+0.j, -0.+0.j, -0.-0.j, -0.+0.j, -0.-0.j, -0.+0.j,  0.+0.j,
        0.-0.j,  0.+0.j,  0.-0.j,  0.-0.j,  0.+0.j, -0.+0.j, -0.+0.j,
       -0.+0.j, -0.-0.j,  0.-0.j,  0.-0.j, -0.+0.j, -0.-0.j,  0.-0.j,
       -0.+0.j, -0.+0.j, -0.+0.j,  0.-0.j,  0.-0.j,  0.+0.j,  0.+0.j,
       -0.-0.j, -0.-0.j,  0.-0.j,  0.+0.j,  0.+0.j, -0.+0.j, -0.-0.j,
       -0.-0.j,  0.-0.j,  0.+0.j, -0.-0.j,  0.-0.j,  0.+0.j, -0.+0.j,
       -0.-0.j, -0.-0.j, -0.-0.j,  0.+0.j,  0.+0.j, -0.+0.j,  0.-0.j,
        0.-0.j, -0.-0.j,  0.-0.j, -0.+0.j,  0.+0.j, -0.-0.j, -0.+0.j,
       -0.-0.j, 50.-

In [ ]:
N = 100
time_series = np.cos(np.linspace(0, 2*np.pi, N, endpoint=False))
fourier_coeff = np.round(np.fft.fft(time_series), 5) / N
np.fft.ifft(fourier_coeff)

array([ 0.01      +0.00000000e+00j,  0.00998027+0.00000000e+00j,
        0.00992115+0.00000000e+00j,  0.00982287+0.00000000e+00j,
        0.00968583+0.00000000e+00j,  0.00951057+0.00000000e+00j,
        0.00929776+2.77555756e-19j,  0.00904827+0.00000000e+00j,
        0.00876307+5.55111512e-19j,  0.00844328+5.55111512e-19j,
        0.00809017+5.55111512e-19j,  0.00770513+1.11022302e-18j,
        0.00728969+0.00000000e+00j,  0.00684547-5.55111512e-19j,
        0.00637424-5.55111512e-19j,  0.00587785+0.00000000e+00j,
        0.00535827+0.00000000e+00j,  0.00481754+5.55111512e-19j,
        0.00425779+5.55111512e-19j,  0.00368125+5.55111512e-19j,
        0.00309017+0.00000000e+00j,  0.0024869 +0.00000000e+00j,
        0.00187381+0.00000000e+00j,  0.00125333+5.27942421e-19j,
        0.00062791-5.27942421e-19j,  0.        +0.00000000e+00j,
       -0.00062791-4.42172976e-19j, -0.00125333+5.27942421e-19j,
       -0.00187381+1.71538891e-19j, -0.0024869 +1.71538891e-19j,
       -0.00309017+1.7153

In [ ]:
N = 8
time_series = np.cos(np.linspace(0, 2*np.pi, N, endpoint=False))
fourier_coeff = np.round(np.fft.fft(time_series), 5) / N
np.fft.ifft(fourier_coeff)

array([ 0.125     +0.j,  0.08838835+0.j,  0.        +0.j, -0.08838835+0.j,
       -0.125     +0.j, -0.08838835+0.j,  0.        +0.j,  0.08838835+0.j])

In [ ]:
N = 8
time_series = np.cos(np.linspace(0, 2*np.pi, N, endpoint=False))
fourier_coeff = np.round(np.fft.fft(time_series), 5)
np.fft.ifft(fourier_coeff)

array([ 1.        +0.j,  0.70710678+0.j,  0.        +0.j, -0.70710678+0.j,
       -1.        +0.j, -0.70710678+0.j,  0.        +0.j,  0.70710678+0.j])