In [85]:
import numpy as np

c = 1
k = 2
P = 2

def residue(x1, x3, y1, y3, omega, beta):

    r1 = P/2 - 3*beta*(x1**3 + x1*y1**2 + x1**2*x3 - x3*y1**2 + 2*x1*y1*y3 + 2*x1*x3**2 + 2*x1*y3**2) - k*x1 + omega*c*y1 + omega**2*x1
    r3 = -beta*(x1**3 - 3*x1*y1**2 + 3*x3**3 + 3*x3*y3**2 + 6*x1**2*x3 + 6*x3*y1**2) - k*x3 + 3*omega*c*y3 + 9*omega**2*x3
    i1 = -3*beta*(x1**2*y1 + y1**3 + x1**2*y3 - y1**2*y3 - 2*x1*x3*y1 + 2*x3**2*y1 + 2*y1*y3**2) - k*y1 - omega*c*x1 + omega**2*y1
    i3 = -beta*(3*x1**2*y1 - y1**3 + 3*x3**2*y3 + 3*y3**3 + 6*x1**2*y3 + 6*y1**2*y3) - k*y3 - 3*omega*c*x3 + 9*omega**2*y3

    return np.array([r1,r3,i1,i3])

def jacobian(x1, x3, y1, y3, omega, beta):

    r1x1 = -3*beta*(3*x1**2 + y1**2 + 2*x1*x3 + 2*y1*y3 + 2*x3**2 + 2*y3**2) - k + omega**2
    r3x1 = -3*beta*(x1**2 - y1**2 + 4*x1*x3)
    i1x1 = -3*beta*(2*x1*y1 + 2*x1*y3 - 2*x3*y1) - omega*c
    i3x1 = -3*beta*(2*x1*y1 + 4*x1*y3)

    r1x3 = -3*beta*(x1**2 - y1**2 + 4*x1*x3)
    r3x3 = -3*beta*(3*x3**2 + y3**2 + 2*x1**2 + 2*y1**2) - k + 9*omega**2 
    i1x3 = -3*beta*(-2*x1*y1 + 4*x3*y1)
    i3x3 = -3*beta*(2*x3*y3) - 3*omega*c

    r1y1 = -3*beta*(2*x1*y1 - 2*x3*y1 + 2*x1*y3) + omega*c
    r3y1 = -3*beta*(-2*x1*y1 + 4*x3*y1)
    i1y1 = -3*beta*(x1**2 + 3*y1**2 - 2*y1*y3 - 2*x1*x3 + 2*x3**2 + 2*y3**2) - k + omega**2
    i3y1 = -3*beta*(x1**2 - y1**2 + 4*y1*y3)

    r1y3 = -3*beta*(2*x1*y1 + 4*x1*y3)
    r3y3 = -3*beta*(2*x3*y3) + 3*omega*c
    i1y3 = -3*beta*(x1**2 - y1**2 + 4*y1*y3)
    i3y3 = -3*beta*(x3**2 + 3*y3**2 + 2*x1**2 + 2*y1**2) - k + 9*omega**2

    return np.array([
        [r1x1,   r1x3,   r1y1,   r1y3],
        [r3x1,   r3x3,   r3y1,   r3y3],
        [i1x1,   i1x3,   i1y1,   i1y3],
        [i3x1,   i3x3,   i3y1,   i3y3]])



In [86]:
q1 = 2 + 1j
q3 = 0 + 0j
omega = 10
beta = 1

print(residue(q1.real, q3.real, q1.imag, q3.imag, omega, beta), "\n")

print(jacobian(q1.real, q3.real, q1.imag, q3.imag, omega, beta), "\n")

[177.  -2.  63. -11.] 

[[ 59.  -9.  -2. -12.]
 [ -9. 868.  12.  30.]
 [-22.  12.  77.  -9.]
 [-12. -30.  -9. 868.]] 



13.0